/// this class will represent the durations in milliseconds [int]
// ignore_for_file: constant_identifier_names

class DurationConsts {
  static const DEFAULT_ANIMATION_DURATION = 450;
  static const ABOVE_DEFAULT_ANIMATION_DURATION = 600;
  static const LONG_ANIMATION_DURATION = 825;
  static const MEDIUM_PLUS_ANIMATION_DURATION = 650;
  static const MEDIUM_ANIMATION_DURATION = 550;
  static const SHORT_ANIMATION_DURATION = 375;
  static const MIN_SHORT_ANIMATION_DURATION = 225;
  static const VERY_SHORT_ANIMATION_DURATION = 150;

  static const SPLASH_DEFAULT_AWAIT_DURATION = 3000;
  static const METRO_DEFAULT_SLIDE_DURATION = 15000;
  static const METRO_INBOX_DEFAULT_SLIDE_DURATION =
      METRO_DEFAULT_SLIDE_DURATION;
  static const METRO_TASK_DEFAULT_SLIDE_DURATION = METRO_DEFAULT_SLIDE_DURATION;
  static const METRO_ELEVATION_DEFAULT_SLIDE_DURATION =
      METRO_DEFAULT_SLIDE_DURATION;
  static const MOVEMENT_CONTROLLER_DURATION = 350;
}
